Generating html reports
gammasim/simtools pull request #1185
Opened 2024-10-07 17:40 UTC by EshitaJoshi

Work in Progress!

Currently reading parameter values, units, and descriptions from telescope_model and generating html reports for a given telescope.

2024-10-21 13:23 UTC, EshitaJoshi commented
This PR adds a new application to simtools `docs_produce_reports.py`, which produces markdown file documentation for a given telescope model at a given site for a given model version.

Example usage:

`python3 simtools/applications/docs_produce_reports.py --model_version 6.0.0 --telescope LSTN-01 --site North` .

The code above will produce an .md file listing the parameter name, value, units, and short descriptions in the `simtools-output` folder.

These markdown files will be available locally, and can be hosted on Gitlab Pages on the `model-parameter-documentation` repository.

2024-10-30 09:26 UTC, GernotMaier commented
Note that above issue is related to a bug in model_parameter.get_parameter_value_with_unit. When using model_parameter.get_parameter_value, everything works.

Just surprising that it worked for you...

2024-10-30 09:27 UTC, GernotMaier commented
Should also discuss how we display values like `nsb_pixel_rate` - which is one float per pixel but all of them are identical. Should we use the sim_telarray stile of "all: nsb_pixel_rate"? Maybe indicating how many values "all" are?

2024-10-30 10:53 UTC, GernotMaier commented
I can confirm that the 'merge main' solved above problem. Thanks!

2025-02-03 08:08 UTC, GernotMaier commented
I have a couple of suggestions.

## New module for markdown generation

Add a new module `simtools.reporting.markdown` where you move  the `generate_markdown_report` and the code after `if args["parameter"]:` in `docs_produce_reports`.

1. `generate_markdown_report` should maybe called `generate_arrray_element_parameter_report` (think about a better name): as it generates the table of all parameters for a given array element and model version. Maybe `generate_production_table`, as it is essentially what we call production tables in the new DB structure: https://gitlab.cta-observatory.org/cta-science/simulations/simulation-model/simulation-models/-/blob/main/simulation-models/productions/6.0.0/LSTN-design.json?ref_type=heads . Note that production tables depend on the `model_version`.
2. the second function would be `generate_model_parameters_report`: it will list for a given `model_parameter` to available values / parameter version.

I am wondering if it would be clearer to also separate this into two different applications.

## Web pages / markdown files:

- add here `parameter_version`: http://model-parameters-documentation-cta-science-simul-a46df0953be8c8.gitlab-pages.cta-observatory.org/productions/6.0.0/LSTN-01.html


## Minor

- suggest to first have `Structure` and then `Camera` in the model reports.
- there should be a simpler way to get the list of model parameters for a given array element now: we essentially only get the production table for a given telescope / model version and loop over all parameters in this tables. I'll help you with that.

2025-02-03 08:45 UTC, GernotMaier commented
Need to discuss src/simtools/reporting/plot_configuration_files/ and find an alternative solution. Not ideal to mix configuration files and code (note also that these model-versions will be very out of date at some point). Any other idea how to configure those plots?

2025-02-19 14:00 UTC, GernotMaier requested changes
Thanks a lot! Below some minor changes and suggestions for improvements. Very close to merge!

2025-02-19 14:00 UTC, GernotMaier commented on src/simtools/reporting/docs_read_parameters.py
> +    def _compare_parameter_across_versions(self, parameter_name):
I am struggling a bit with this function (there is no unit test?):

- if a parameter does not change between models, what is returned?
- a TelescopeModel instance is generate for each model version; this will lead to read out all parameters relevant for this telescope and model parameter. Do I understand that we only want the parameter dict for one version? 

I suggest for now the following (as this PR has been open so long):

- add a unit test for _compare_parameter_across_versions
- don't change the code, but open an issue saying "Improve efficiency of ..." 

I think it should be possible to get for a given parameter first:

- all model versions for which this parameter is defined (not all parameters need to be defined for all model versions)
- for each of the selected model version the relevant parameter version
- then using db.get_model_parameter() querying the DB for this parameter version only (we could test if can change this function to allow a list of parameter versions in the query).

2025-02-19 14:00 UTC, GernotMaier commented on src/simtools/utils/names.py
This is ok, but just to let you know that a very similar change (with extension to calibration and other instrument classes) in PR #1379

2025-02-19 14:00 UTC, GernotMaier commented
@EshitaJoshi - thanks for this, very nice.

My comments are mostly about wording.

Should discuss the naming of the two reporting applications. I am actually not entirely sure about what the differences are (even from reading the docstrings), is it:

- `docs_generate_model_parameter_report` generates a report for a given array element (telescope) and model version? 
- `docs_produce_reports` generates a report for a single model parameter including all parameter versions?

I somehow expected exactly the opposite from the naming. Could you have another thought on this and suggest a better naming? (also 'generate', 'produce').

2025-02-19 15:21 UTC, EshitaJoshi commented on tests/unit_tests/reporting/test_read_parameters.py
> +    with pytest.raises(FileNotFoundError):
Added match

2025-02-19 15:22 UTC, EshitaJoshi commented on src/simtools/reporting/docs_read_parameters.py
> +        data = self.get_telescope_parameter_data(self.telescope_model)
Changed 'telescope' to 'array_element' in the function naming

2025-02-19 15:22 UTC, EshitaJoshi commented on src/simtools/model/model_parameter.py
> +        self.design_model = self.db.get_design_model(self.model_version, self.name)
Added ```collection```

2025-02-19 15:23 UTC, EshitaJoshi commented on src/simtools/db/db_handler.py
> +        Get list array elements for a given model version and collection from the DB.
Updated docstring

2025-02-19 15:23 UTC, EshitaJoshi commented on src/simtools/applications/docs_produce_reports.py
> +The reports are then uploaded as GitLab Pages using GitLab's CI workflow.
removed gitlab from docstring

2025-02-20 11:01 UTC, GernotMaier commented on src/simtools/reporting/docs_read_parameters.py
> +    def _compare_parameter_across_versions(self, parameter_name):
Did you open an issue on this topic? Or any other idea?

2025-02-20 11:04 UTC, GernotMaier approved these changes
Approved - but please see my question below and if needed open an issue.

2025-02-20 18:00 UTC, merged