Fix label corsika histograms
gammasim/simtools pull request #638
Opened 2023-10-16 11:55 UTC by VictorBarbosaMartins

Closes #637.

Fixed the y label of the 1D density histogram, and also the y label of other 2D histograms which were appearing as units "()". We should come up with nicer names for the histograms instead of writing the name of the module function as the title of the histogram. It is probably better to do that in another PR.

Thanks.

2023-10-16 12:47 UTC, GernotMaier requested changes
see comment on the superscript.

2023-10-16 12:47 UTC, GernotMaier commented on simtools/corsika/corsika_histograms_visualize.py
> +                f"{histograms_instance._dict_1D_distributions[property_name]['edges unit']}$^{-2}$)"
I think the superscript did not work:

<img width="62" alt="Screenshot 2023-10-16 at 14 46 48" src="https://github.com/gammasim/simtools/assets/14001688/29fcfd7f-91a8-4dcd-a9d1-29d156397dea">

2023-10-16 15:20 UTC, GernotMaier approved these changes
Very minor comment, but all good!

2023-10-16 15:20 UTC, GernotMaier commented on simtools/utils/general.py
> +        The values of the x axis (histogram bin_edges) on the ground.
I think in the comment you don't need the underscore in `bin edges`

2023-10-16 15:20 UTC, GernotMaier commented on simtools/utils/general.py
> +        The values of the y axis (histogram bin_edges) on the ground.
Same as above

2023-10-16 15:20 UTC, GernotMaier commented on simtools/utils/general.py
> +        The bin_edges of the 1D histogram with size = int(max_dist/bin_size) + 1.
Same as above

2023-10-16 15:20 UTC, GernotMaier commented on tests/unit_tests/corsika/test_corsika_histograms.py
> +    # The bin_edges should be the same
same as above

2023-10-16 15:20 UTC, GernotMaier commented on tests/unit_tests/corsika/test_corsika_histograms.py
> +    # (bin_edges of hist)
same as above

2023-10-17 08:20 UTC, VictorBarbosaMartins commented
Thanks for the remaining comments and the approval. I implemented them and the tests are passing, so I am merging the PR.

2023-10-17 08:21 UTC, merged