Improve plot simtel histograms
gammasim/simtools pull request #655
Opened 2023-10-24 13:39 UTC by VictorBarbosaMartins

Closes #652.

Implemented the functionality that allows the plot simtel histograms application to receive a list of histograms (or one histogram) instead of only a text file with the histogram file names in it. It is more flexible now.

2023-10-25 08:00 UTC, tobiaskleiner approved these changes

2023-10-26 09:55 UTC, orelgueta requested changes
See comment about a specific line and the discussion in person.

2023-10-26 12:00 UTC, VictorBarbosaMartins commented on simtools/applications/plot_simtel_histograms.py
> +        "--hist_file_names",
Hi Orel. Thanks for this comment. I simplified the code now, I think that is what you meant. Please have a second look.

2023-10-26 15:13 UTC, orelgueta approved these changes
Looks good now!

2023-10-26 15:22 UTC, merged