Hdf5 simtel histograms
gammasim/simtools pull request #664
Opened 2023-11-06 18:06 UTC by VictorBarbosaMartins

### Still a draft pull request to close #663

### To dos
- [ ] Investigate whether we need to support all the available histograms or whether we can focus on the simulated events and use ctapipe containers as Karl suggested (https://github.com/gammasim/simtools/issues/663#issuecomment-1794981656)
- [ ] Implement the new functionality of exporting to hdf5 in the application
- [ ] Complement with the integration tests

2023-11-07 16:22 UTC, VictorBarbosaMartins commented
Tests seem to be passing so this is ready for review. Please note the extensive description of the PR, facilitating the review process.

2023-11-08 12:47 UTC, GernotMaier commented
Note that several warnings are generated when running the application:

```
INFO::generate_simtel_array_histograms(l125)::main::Starting the application.
INFO::base(l60)::__init__::Opening new file tests/resources/run2_gamma_za20deg_azm0deg-North-Prod5_test-production-5.hdata.zst
INFO::base(l93)::__init__::Found zstd compressed file
/Users/maierg/DESYCloud/CTA/Pipelines/MC-Pipeline/gammasim-tools/simtools/simtools/applications/generate_simtel_array_histograms.py:176: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`). Consider using `matplotlib.pyplot.close()`.
  fig, axs = plt.subplots(1, n_lists, figsize=(6 * n_lists, 6))
INFO::generate_simtel_array_histograms(l185)::main::Wrote histograms to the pdf file /Users/maierg/DESYCloud/CTA/Pipelines/MC-Pipeline/gammasim-tools/simtools/simtools-output/generate_simtel_array_histograms/application-plots/test_hist_hdata.pdf
INFO::generate_simtel_array_histograms(l188)::main::Wrote histograms to the hdf5 file /Users/maierg/DESYCloud/CTA/Pipelines/MC-Pipeline/gammasim-tools/simtools/simtools-output/generate_simtel_array_histograms/application-plots/test_hist_hdata.hdf5
/Users/maierg/miniconda3/envs/simtools-dev/lib/python3.9/site-packages/tables/attributeset.py:459: NaturalNameWarning: object name is not a valid Python identifier: 'x bin edges unit'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)
/Users/maierg/miniconda3/envs/simtools-dev/lib/python3.9/site-packages/tables/attributeset.py:459: NaturalNameWarning: object name is not a valid Python identifier: 'y bin edges unit'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)
INFO::generate_simtel_array_histograms(l192)::main::Finalizing the application. Total time needed: 159s.
```

Wondering if we can ommit them.

2023-11-08 14:08 UTC, GernotMaier requested changes
Requesting some minor changes. See also my comments on the warnings.

2023-11-13 09:28 UTC, VictorBarbosaMartins commented on simtools/applications/generate_simtel_array_histograms.py
> +    This application plots and prints sim_telarray histograms into pdf file.
Good point. I changed it now.

2023-11-13 09:28 UTC, VictorBarbosaMartins commented on simtools/applications/generate_simtel_array_histograms.py
> +        "--hdf5", help="Save histograms into hdf5 files.", action="store_true", required=False
It is only one hdf5 file. I updated the text now.

2023-11-13 09:28 UTC, VictorBarbosaMartins commented on simtools/applications/generate_simtel_array_histograms.py
> +    if not config_parser["pdf"]:
I started implementing that and then I remembered why I did not use it before. "Mutually exclusive" does not allow both options to be passed (see last comment in the best answer in the stackoverflow link). I havent found a better solution for that, so unless you have one, I would keep it like this.

2023-11-13 09:28 UTC, VictorBarbosaMartins commented on simtools/applications/generate_simtel_array_histograms.py
> +    initial_time = time.time()
It depends on the length of the file lists passed but probably not a big deal. This is reminiscent from the corsika histograms, where we in fact build the histograms (more time consuming). Thus, I am removing it from here as suggested.

2023-11-13 09:28 UTC, VictorBarbosaMartins commented on simtools/applications/generate_simtel_array_histograms.py
> +        if Path(one_file).is_file():
Done.

2023-11-13 09:29 UTC, VictorBarbosaMartins commented
> Note that several warnings are generated when running the application:
> 
> ```
> INFO::generate_simtel_array_histograms(l125)::main::Starting the application.
> INFO::base(l60)::__init__::Opening new file tests/resources/run2_gamma_za20deg_azm0deg-North-Prod5_test-production-5.hdata.zst
> INFO::base(l93)::__init__::Found zstd compressed file
> /Users/maierg/DESYCloud/CTA/Pipelines/MC-Pipeline/gammasim-tools/simtools/simtools/applications/generate_simtel_array_histograms.py:176: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`). Consider using `matplotlib.pyplot.close()`.
>   fig, axs = plt.subplots(1, n_lists, figsize=(6 * n_lists, 6))
> INFO::generate_simtel_array_histograms(l185)::main::Wrote histograms to the pdf file /Users/maierg/DESYCloud/CTA/Pipelines/MC-Pipeline/gammasim-tools/simtools/simtools-output/generate_simtel_array_histograms/application-plots/test_hist_hdata.pdf
> INFO::generate_simtel_array_histograms(l188)::main::Wrote histograms to the hdf5 file /Users/maierg/DESYCloud/CTA/Pipelines/MC-Pipeline/gammasim-tools/simtools/simtools-output/generate_simtel_array_histograms/application-plots/test_hist_hdata.hdf5
> /Users/maierg/miniconda3/envs/simtools-dev/lib/python3.9/site-packages/tables/attributeset.py:459: NaturalNameWarning: object name is not a valid Python identifier: 'x bin edges unit'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
>   check_attribute_name(name)
> /Users/maierg/miniconda3/envs/simtools-dev/lib/python3.9/site-packages/tables/attributeset.py:459: NaturalNameWarning: object name is not a valid Python identifier: 'y bin edges unit'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
>   check_attribute_name(name)
> INFO::generate_simtel_array_histograms(l192)::main::Finalizing the application. Total time needed: 159s.
> ```
> 
> Wondering if we can ommit them.

These are not warnings but log information. I personally prefer to see what is being doing in the application as it is running. Other applications are also using it:
![Screenshot 2023-11-13 at 09 35 29](https://github.com/gammasim/simtools/assets/50831535/6a61cfc6-504c-473f-9e92-b571282cbd1f)

If you prefer to move this kind of info all to debug level, I would suggest to open an issue for that.

2023-11-13 09:42 UTC, VictorBarbosaMartins commented on simtools/applications/generate_simtel_array_histograms.py
> +    logger.info(
I personally always prefer to have a statement closing the application, but lets not discuss that again. I removed this last log info.

2023-11-13 13:29 UTC, GernotMaier commented
I've fixed the sphinx build errors:

- add ctapipe to imports which are part of `auto_mock_import` (this prevent sphinx from importing models and trying to extract documentation; one issue is in ctapipe (which doesn't use sphinx))
- fix sphinx format errors in docstrings in applications/generate_simtel_array_histograms.py.

You need to align intend in docstrings. Not:

```
    hist_file_names (str, optional)
        Name of the histogram files to be plotted.
        It can be given as the histogram file names (more than one option allowed) or as a text
            file with the names of the histogram files in it.
```

but

```
    hist_file_names (str, optional)
        Name of the histogram files to be plotted.
        It can be given as the histogram file names (more than one option allowed) or as a text
        file with the names of the histogram files in it.
    figure_name (str, required)
        File name for the pdf output (without extension).
```

- removed non-standard ascii in comment in simtools/camera_efficiency.py
- fixed RST syntax errors - care needs to be taken:

Not

```
generate_simtel_array_histograms
====================
```

but

```
generate_simtel_array_histograms
================================
```

I've also added a `-v` option to the sphinx build command in the Makefile to make debugging easier.

Please have a look and let me know if this is all ok.

2023-11-13 13:47 UTC, VictorBarbosaMartins commented
Thank you for spotting these issues and fixing them. I am fine with these changes! (though you would need to approve if you are fine with the other changes)

2023-11-13 13:52 UTC, GernotMaier approved these changes

2023-11-13 13:52 UTC, GernotMaier commented on simtools/applications/generate_simtel_array_histograms.py
> +    if not config_parser["pdf"]:
OK!

2023-11-13 14:14 UTC, merged